artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://drive.google.com/file/d/1bnvvj1y6Rr1_HZc3-QhWC596hWYR8kCj/view?usp=sharing'
  local_data_file: 'artifacts/data_ingestion/data.zip'
  unzip_dir: 'artifacts/data_ingestion'